/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#d3e4fe",
        "surface-container-lowest": "#000f21",
        "on-tertiary-fixed-variant": "#653e00",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-highest": "#26364a",
        "primary-fixed": "#dae2fd",
        "surface-tint": "#bec6e0",
        "on-surface": "#d3e4fe",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-dim": "#031427",
        "error-container": "#93000a",
        "secondary-container": "#464a4b",
        "on-secondary-fixed": "#191c1e",
        tertiary: "#ffb95f",
        "on-secondary": "#2d3133",
        "secondary-fixed-dim": "#c4c7c9",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#798098",
        "on-surface-variant": "#c6c6cd",
        background: "#031427",
        "secondary-fixed": "#e0e3e5",
        "primary-fixed-dim": "#bec6e0",
        "inverse-on-surface": "#213145",
        outline: "#909097",
        "on-tertiary": "#472a00",
        primary: "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "outline-variant": "#45464d",
        secondary: "#c4c7c9",
        "primary-container": "#0f172a",
        "inverse-primary": "#565e74",
        "on-tertiary-container": "#b47300",
        "tertiary-fixed": "#ffddb8",
        "surface-bright": "#2a3a4f",
        "on-secondary-container": "#b6b9bb",
        "tertiary-container": "#251400",
        "on-error": "#690005",
        "on-primary-fixed": "#131b2e",
        "on-background": "#d3e4fe",
        "surface-container": "#102034",
        "surface-variant": "#26364a",
        "surface-container-low": "#0b1c30",
        error: "#ffb4ab",
        "on-primary": "#283044",
        "surface-container-high": "#1b2b3f",
        surface: "#031427",
        "on-secondary-fixed-variant": "#444749",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "container-max": "1440px",
        gutter: "24px",
        "margin-desktop": "40px",
        "margin-mobile": "16px",
        unit: "4px",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-lg": ["Inter"],
        "label-caps": ["JetBrains Mono"],
        "body-sm": ["Inter"],
        "display-lg": ["Inter"],
        "data-mono": ["JetBrains Mono"],
        "headline-md": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-mono": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
